# -*- coding: utf-8 -*-
"""Medicine_Recommendation.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Oe_ku__72-ZIEk20b8vQjlTJ9vPKSf5
"""

from google.colab import files

uploaded = files.upload()  # Ye ek button dikhayega, zip select karo

import zipfile
import os

zip_file = "medicine_app.zip"  # Tumhari uploaded zip ka name
extract_path = "/content/medicine_app"  # Jahan extract karna hai

with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

# Check files
os.listdir(extract_path)

import os
import pickle

BASE_DIR = "/content/medicine_app"

model = pickle.load(open(os.path.join(BASE_DIR, "model.pkl"), "rb"))
vectorizer = pickle.load(open(os.path.join(BASE_DIR, "vectorizer.pkl"), "rb"))

# Pehle DummyModel define karo (ya jo class thi)
class DummyModel:
    def predict(self, X):
        return ["disease1"]*len(X)

# Phir load karo
import pickle, os
BASE_DIR = "/content/medicine_app"
model = pickle.load(open(os.path.join(BASE_DIR, "model.pkl"), "rb"))

import json
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
import pickle
import os

BASE_DIR = "/content/medicine_app"

with open(os.path.join(BASE_DIR, "disease.json")) as f:
    diseases = json.load(f)

X, y = [], []
for disease, info in diseases.items():
    for keyword in info["keywords"]:
        X.append(keyword)
        y.append(disease)

vectorizer = TfidfVectorizer()
X_vect = vectorizer.fit_transform(X)

clf = MultinomialNB()
clf.fit(X_vect, y)

# Save trained model
with open(os.path.join(BASE_DIR, "model.pkl"), "wb") as f:
    pickle.dump(clf, f)
with open(os.path.join(BASE_DIR, "vectorizer.pkl"), "wb") as f:
    pickle.dump(vectorizer, f)

import json

with open("/content/medicine_app/disease.json") as f:
    diseases = json.load(f)

print(diseases)

{
    "fever": {
        "keywords": ["fever", "high temperature", "hot", "body ache"],
        "medicine": ["Paracetamol", "Panadol"],
        "precautions": ["Drink water", "Rest"]
    },
    "cold": {
        "keywords": ["cold", "sneeze", "runny nose", "cough"],
        "medicine": ["Cetirizine"],
        "precautions": ["Avoid cold drinks", "Rest"]
    }
}

{
  "fever": {
    "keywords": ["fever", "bukhar", "high temperature"],
    "medicine": ["Paracetamol", "Panadol"],
    "precautions": ["Drink water", "Rest", "Avoid cold drinks"]
  },
  "cold": {
    "keywords": ["cold", "sardi", "runny nose"],
    "medicine": ["Cetirizine"],
    "precautions": ["Rest", "Avoid cold drinks", "Drink warm water"]
  },
  "headache": {
    "keywords": ["headache", "sir dard", "migraine"],
    "medicine": ["Paracetamol", "Ibuprofen"],
    "precautions": ["Rest in dark room", "Drink water"]
  },
  "cough": {
    "keywords": ["cough", "khansi", "throat irritation"],
    "medicine": ["Cough Syrup", "Dextromethorphan"],
    "precautions": ["Drink warm water", "Avoid cold drinks"]
  },
  "diabetes": {
    "keywords": ["diabetes", "high sugar", "blood sugar"],
    "medicine": ["Insulin", "Metformin"],
    "precautions": ["Avoid sugar", "Exercise regularly"]
  },
  "hypertension": {
    "keywords": ["hypertension", "high blood pressure", "bp"],
    "medicine": ["Amlodipine", "Losartan"],
    "precautions": ["Avoid salty food", "Exercise regularly"]
  },
  "asthma": {
    "keywords": ["asthma", "breathing difficulty", "wheezing"],
    "medicine": ["Salbutamol", "Inhaler"],
    "precautions": ["Avoid dust", "Avoid smoke"]
  },
  "allergy": {
    "keywords": ["allergy", "skin rash", "sneezing"],
    "medicine": ["Cetirizine", "Loratadine"],
    "precautions": ["Avoid allergens", "Use antihistamines"]
  },
  "back_pain": {
    "keywords": ["back pain", "lumbar pain", "lower back"],
    "medicine": ["Ibuprofen", "Paracetamol"],
    "precautions": ["Use correct posture", "Do light exercise"]
  },
  "stomachache": {
    "keywords": ["stomachache", "gas", "indigestion"],
    "medicine": ["Antacids", "Omeprazole"],
    "precautions": ["Eat light food", "Avoid oily food"]
  },
  "migraine": {
    "keywords": ["migraine", "headache", "nausea"],
    "medicine": ["Ibuprofen", "Sumatriptan"],
    "precautions": ["Rest in dark room", "Avoid stress"]
  },
  "anemia": {
    "keywords": ["anemia", "low hemoglobin", "fatigue"],
    "medicine": ["Iron supplements", "Vitamin B12"],
    "precautions": ["Eat iron-rich food", "Avoid tea with meals"]
  },
  "depression": {
    "keywords": ["depression", "sadness", "mental health"],
    "medicine": ["SSRIs", "Therapy"],
    "precautions": ["Talk to a therapist", "Exercise"]
  },
  "anxiety": {
    "keywords": ["anxiety", "nervousness", "worry"],
    "medicine": ["SSRIs", "Benzodiazepines"],
    "precautions": ["Meditation", "Avoid caffeine"]
  },
  "insomnia": {
    "keywords": ["insomnia", "sleeplessness", "trouble sleeping"],
    "medicine": ["Melatonin", "Sleep aids"],
    "precautions": ["Avoid screens before bed", "Maintain sleep schedule"]
  },
  "bronchitis": {
    "keywords": ["bronchitis", "cough", "chest congestion"],
    "medicine": ["Antibiotics", "Cough syrup"],
    "precautions": ["Avoid smoke", "Drink warm fluids"]
  },
  "pneumonia": {
    "keywords": ["pneumonia", "lung infection", "cough with phlegm"],
    "medicine": ["Antibiotics", "Hospital care"],
    "precautions": ["Rest", "Stay hydrated"]
  },
  "diarrhea": {
    "keywords": ["diarrhea", "loose stools", "stomach infection"],
    "medicine": ["ORS", "Loperamide"],
    "precautions": ["Drink plenty of fluids", "Eat light food"]
  },
  "vomiting": {
    "keywords": ["vomiting", "nausea", "throwing up"],
    "medicine": ["Ondansetron", "Hydration"],
    "precautions": ["Rest", "Drink water slowly"]
  },
  "urinary_tract_infection": {
    "keywords": ["uti", "urinary infection", "burning urination"],
    "medicine": ["Ciprofloxacin", "Nitrofurantoin"],
    "precautions": ["Drink plenty of water", "Avoid irritants"]
  },
  "kidney_stone": {
    "keywords": ["kidney stone", "renal stone", "painful urination"],
    "medicine": ["Painkillers", "Hydration"],
    "precautions": ["Drink water", "Avoid excessive salt"]
  },
  "liver_disease": {
    "keywords": ["liver disease", "hepatitis", "jaundice"],
    "medicine": ["Medical care", "Liver supplements"],
    "precautions": ["Avoid alcohol", "Healthy diet"]
  },
  "thyroid": {
    "keywords": ["thyroid", "hypothyroidism", "hyperthyroidism"],
    "medicine": ["Levothyroxine", "Thyronorm"],
    "precautions": ["Regular checkups", "Avoid certain foods"]
  },
  "obesity": {
    "keywords": ["obesity", "overweight", "fat"],
    "medicine": ["Diet plan", "Exercise"],
    "precautions": ["Regular exercise", "Healthy diet"]
  },
  "arthritis": {
    "keywords": ["arthritis", "joint pain", "osteoarthritis"],
    "medicine": ["Ibuprofen", "Naproxen"],
    "precautions": ["Exercise regularly", "Use support braces"]
  },
  "flu": {
    "keywords": ["flu", "influenza", "fever and cough"],
    "medicine": ["Paracetamol", "Antiviral meds"],
    "precautions": ["Rest", "Stay hydrated"]
  },
  "chickenpox": {
    "keywords": ["chickenpox", "rash", "itching"],
    "medicine": ["Calamine lotion", "Antihistamines"],
    "precautions": ["Avoid scratching", "Rest"]
  },
  "measles": {
    "keywords": ["measles", "rash", "fever"],
    "medicine": ["Supportive care", "Vitamin A"],
    "precautions": ["Isolate patient", "Rest"]
  },
  "dengue": {
    "keywords": ["dengue", "high fever", "bleeding"],
    "medicine": ["Paracetamol", "Hospital care"],
    "precautions": ["Avoid aspirin", "Hydrate"]
  },
  "malaria": {
    "keywords": ["malaria", "mosquito fever", "chills"],
    "medicine": ["Artemisinin", "Hospital care"],
    "precautions": ["Use mosquito nets", "Hydrate"]
  },
  "covid19": {
    "keywords": ["covid", "corona", "sars-cov-2"],
    "medicine": ["Supportive care", "Isolation"],
    "precautions": ["Wear mask", "Sanitize hands"]
  },
  "typhoid": {
    "keywords": ["typhoid", "fever", "abdominal pain"],
    "medicine": ["Ciprofloxacin", "Azithromycin"],
    "precautions": ["Drink clean water", "Avoid street food"]
  },
  "hepatitis_b": {
    "keywords": ["hepatitis b", "liver infection", "jaundice"],
    "medicine": ["Antivirals", "Supportive care"],
    "precautions": ["Avoid alcohol", "Rest"]
  },
  "hepatitis_c": {
    "keywords": ["hepatitis c", "liver infection", "jaundice"],
    "medicine": ["Antivirals", "Supportive care"],
    "precautions": ["Avoid alcohol", "Rest"]
  },
  "eczema": {
    "keywords": ["eczema", "skin rash", "itching"],
    "medicine": ["Moisturizers", "Steroid creams"],
    "precautions": ["Avoid allergens", "Keep skin moisturized"]
  },
  "psoriasis": {
    "keywords": ["psoriasis", "skin scaling", "itching"],
    "medicine": ["Topical creams", "Phototherapy"],
    "precautions": ["Moisturize skin", "Avoid triggers"]
  },
  "gastroenteritis": {
    "keywords": ["gastroenteritis", "diarrhea", "vomiting"],
    "medicine": ["ORS", "Hydration"],
    "precautions": ["Drink fluids", "Eat light food"]
  },
  "migraine_chronic": {
    "keywords": ["chronic migraine", "headache", "nausea"],
    "medicine": ["Triptans", "Ibuprofen"],
    "precautions": ["Avoid stress", "Rest in dark room"]
  }
}

import json

# Suppose tumhare pass updated data ye hai
diseases = {

  "fever": {
    "keywords": ["fever", "bukhar", "high temperature"],
    "medicine": ["Paracetamol", "Panadol"],
    "precautions": ["Drink water", "Rest", "Avoid cold drinks"]
  },
  "cold": {
    "keywords": ["cold", "sardi", "runny nose"],
    "medicine": ["Cetirizine"],
    "precautions": ["Rest", "Avoid cold drinks", "Drink warm water"]
  },
  "headache": {
    "keywords": ["headache", "sir dard", "migraine"],
    "medicine": ["Paracetamol", "Ibuprofen"],
    "precautions": ["Rest in dark room", "Drink water"]
  },
  "cough": {
    "keywords": ["cough", "khansi", "throat irritation"],
    "medicine": ["Cough Syrup", "Dextromethorphan"],
    "precautions": ["Drink warm water", "Avoid cold drinks"]
  },
  "diabetes": {
    "keywords": ["diabetes", "high sugar", "blood sugar"],
    "medicine": ["Insulin", "Metformin"],
    "precautions": ["Avoid sugar", "Exercise regularly"]
  },
  "hypertension": {
    "keywords": ["hypertension", "high blood pressure", "bp"],
    "medicine": ["Amlodipine", "Losartan"],
    "precautions": ["Avoid salty food", "Exercise regularly"]
  },
  "asthma": {
    "keywords": ["asthma", "breathing difficulty", "wheezing"],
    "medicine": ["Salbutamol", "Inhaler"],
    "precautions": ["Avoid dust", "Avoid smoke"]
  },
  "allergy": {
    "keywords": ["allergy", "skin rash", "sneezing"],
    "medicine": ["Cetirizine", "Loratadine"],
    "precautions": ["Avoid allergens", "Use antihistamines"]
  },
  "back_pain": {
    "keywords": ["back pain", "lumbar pain", "lower back"],
    "medicine": ["Ibuprofen", "Paracetamol"],
    "precautions": ["Use correct posture", "Do light exercise"]
  },
  "stomachache": {
    "keywords": ["stomachache", "gas", "indigestion"],
    "medicine": ["Antacids", "Omeprazole"],
    "precautions": ["Eat light food", "Avoid oily food"]
  },
  "migraine": {
    "keywords": ["migraine", "headache", "nausea"],
    "medicine": ["Ibuprofen", "Sumatriptan"],
    "precautions": ["Rest in dark room", "Avoid stress"]
  },
  "anemia": {
    "keywords": ["anemia", "low hemoglobin", "fatigue"],
    "medicine": ["Iron supplements", "Vitamin B12"],
    "precautions": ["Eat iron-rich food", "Avoid tea with meals"]
  },
  "depression": {
    "keywords": ["depression", "sadness", "mental health"],
    "medicine": ["SSRIs", "Therapy"],
    "precautions": ["Talk to a therapist", "Exercise"]
  },
  "anxiety": {
    "keywords": ["anxiety", "nervousness", "worry"],
    "medicine": ["SSRIs", "Benzodiazepines"],
    "precautions": ["Meditation", "Avoid caffeine"]
  },
  "insomnia": {
    "keywords": ["insomnia", "sleeplessness", "trouble sleeping"],
    "medicine": ["Melatonin", "Sleep aids"],
    "precautions": ["Avoid screens before bed", "Maintain sleep schedule"]
  },
  "bronchitis": {
    "keywords": ["bronchitis", "cough", "chest congestion"],
    "medicine": ["Antibiotics", "Cough syrup"],
    "precautions": ["Avoid smoke", "Drink warm fluids"]
  },
  "pneumonia": {
    "keywords": ["pneumonia", "lung infection", "cough with phlegm"],
    "medicine": ["Antibiotics", "Hospital care"],
    "precautions": ["Rest", "Stay hydrated"]
  },
  "diarrhea": {
    "keywords": ["diarrhea", "loose stools", "stomach infection"],
    "medicine": ["ORS", "Loperamide"],
    "precautions": ["Drink plenty of fluids", "Eat light food"]
  },
  "vomiting": {
    "keywords": ["vomiting", "nausea", "throwing up"],
    "medicine": ["Ondansetron", "Hydration"],
    "precautions": ["Rest", "Drink water slowly"]
  },
  "urinary_tract_infection": {
    "keywords": ["uti", "urinary infection", "burning urination"],
    "medicine": ["Ciprofloxacin", "Nitrofurantoin"],
    "precautions": ["Drink plenty of water", "Avoid irritants"]
  },
  "kidney_stone": {
    "keywords": ["kidney stone", "renal stone", "painful urination"],
    "medicine": ["Painkillers", "Hydration"],
    "precautions": ["Drink water", "Avoid excessive salt"]
  },
  "liver_disease": {
    "keywords": ["liver disease", "hepatitis", "jaundice"],
    "medicine": ["Medical care", "Liver supplements"],
    "precautions": ["Avoid alcohol", "Healthy diet"]
  },
  "thyroid": {
    "keywords": ["thyroid", "hypothyroidism", "hyperthyroidism"],
    "medicine": ["Levothyroxine", "Thyronorm"],
    "precautions": ["Regular checkups", "Avoid certain foods"]
  },
  "obesity": {
    "keywords": ["obesity", "overweight", "fat"],
    "medicine": ["Diet plan", "Exercise"],
    "precautions": ["Regular exercise", "Healthy diet"]
  },
  "arthritis": {
    "keywords": ["arthritis", "joint pain", "osteoarthritis"],
    "medicine": ["Ibuprofen", "Naproxen"],
    "precautions": ["Exercise regularly", "Use support braces"]
  },
  "flu": {
    "keywords": ["flu", "influenza", "fever and cough"],
    "medicine": ["Paracetamol", "Antiviral meds"],
    "precautions": ["Rest", "Stay hydrated"]
  },
  "chickenpox": {
    "keywords": ["chickenpox", "rash", "itching"],
    "medicine": ["Calamine lotion", "Antihistamines"],
    "precautions": ["Avoid scratching", "Rest"]
  },
  "measles": {
    "keywords": ["measles", "rash", "fever"],
    "medicine": ["Supportive care", "Vitamin A"],
    "precautions": ["Isolate patient", "Rest"]
  },
  "dengue": {
    "keywords": ["dengue", "high fever", "bleeding"],
    "medicine": ["Paracetamol", "Hospital care"],
    "precautions": ["Avoid aspirin", "Hydrate"]
  },
  "malaria": {
    "keywords": ["malaria", "mosquito fever", "chills"],
    "medicine": ["Artemisinin", "Hospital care"],
    "precautions": ["Use mosquito nets", "Hydrate"]
  },
  "covid19": {
    "keywords": ["covid", "corona", "sars-cov-2"],
    "medicine": ["Supportive care", "Isolation"],
    "precautions": ["Wear mask", "Sanitize hands"]
  },
  "typhoid": {
    "keywords": ["typhoid", "fever", "abdominal pain"],
    "medicine": ["Ciprofloxacin", "Azithromycin"],
    "precautions": ["Drink clean water", "Avoid street food"]
  },
  "hepatitis_b": {
    "keywords": ["hepatitis b", "liver infection", "jaundice"],
    "medicine": ["Antivirals", "Supportive care"],
    "precautions": ["Avoid alcohol", "Rest"]
  },
  "hepatitis_c": {
    "keywords": ["hepatitis c", "liver infection", "jaundice"],
    "medicine": ["Antivirals", "Supportive care"],
    "precautions": ["Avoid alcohol", "Rest"]
  },
  "eczema": {
    "keywords": ["eczema", "skin rash", "itching"],
    "medicine": ["Moisturizers", "Steroid creams"],
    "precautions": ["Avoid allergens", "Keep skin moisturized"]
  },
  "psoriasis": {
    "keywords": ["psoriasis", "skin scaling", "itching"],
    "medicine": ["Topical creams", "Phototherapy"],
    "precautions": ["Moisturize skin", "Avoid triggers"]
  },
  "gastroenteritis": {
    "keywords": ["gastroenteritis", "diarrhea", "vomiting"],
    "medicine": ["ORS", "Hydration"],
    "precautions": ["Drink fluids", "Eat light food"]
  },
  "migraine_chronic": {
    "keywords": ["chronic migraine", "headache", "nausea"],
    "medicine": ["Triptans", "Ibuprofen"],
    "precautions": ["Avoid stress", "Rest in dark room"]
  }
}


    # baaki 39 diseases bhi yaha honi chahiye


# Save karne ke liye
with open("/content/medicine_app/disease.json", "w") as f:
    json.dump(diseases, f, indent=4)

print("Updated disease.json saved successfully!")

